LLVM 15 WIP
Disables opaque pointers, which are the default in LLVM 15. This
provides type assertions that the type we pass to Load and GEP
operations matches the pointer type.

Removes calls to deprecated function getPointerElementType.

Fixes calls to CreateLoad, and Create*GEP* functions that now require a
type (and not null).

Fixes unqualified-std-cast-call error when compiling with clang
runtime-profile-counters.h:661:29: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    Event event = make_pair(move(label), sw_.ElapsedTime() + offset_);
                            ^
                            std::
runtime-profile-counters.h:663:26: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    events_.emplace_back(move(event));
                         ^
                         std::

Change-Id: Ib237e7a2ccc3a178a50a2c5f0555d5fdb109b98b